name: app_miscelanea
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"







dependencies:

  mockito: ^5.4.0
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  dio: ^5.1.1
  http_mock_adapter: ^0.4.4
  nock: ^1.2.2
 

flutter_launcher_icons: 
    image_path_android: 'assets/icons/app_icon.png'
    android: true
    min_sdk_android: 21
    adaptive_icon_background: 

dev_dependencies:
  
  build_runner: ^2.3.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

       


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
